version: '3.5'

networks:
  codesmith-network:
    name: codesmith

volumes:
    allianceSeeds_postgres_data:
    codesmith-pgadmin-data:
    
services:

  allianceseeds-api:
    container_name: allianceseeds-api
    hostname: allianceseeds-api
    image: allianceseeds-api:1.0.4
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        version: 1.0.4
    networks:
      - codesmith-network
    ports:
      - "9090:9090"
    env_file:
      - .env.docker
    volumes:
      - ./service_logs:/accutrak/toolbox/logs
    depends_on:
      - allianceSeeds-db


  allianceSeeds-db:
    container_name: allianceSeeds-db
    hostname: allianceSeeds-db
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - codesmith-network
    ports:
      - "5432:5432"
    volumes:
      - allianceSeeds_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.docker

  pgadmin:
    container_name: codesmith-pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - codesmith-network
    ports:
      - "8889:80"
    env_file:
      - .env.docker
    volumes:
      - codesmith-pgadmin-data:/var/lib/pgadmin




